from selenium.webdriver.common.by import By


class CheackoutLocators:
    LOGIN_USER_EMAIL = (By.ID , 'input-email')
    LOGIN_PASSWORD = (By.ID, 'input-password')
    LOGIN_BTN = (By.ID, 'button-login')
    ERROR_MESSAGE_LOG_IN = (By.CSS_SELECTOR, 'div.panel-body div.alert')
    RADIO_REGISTER_USER = (By.CSS_SELECTOR, 'input[value="register"]')
    BTN_CONTINUE_REGISTER = (By.CSS_SELECTOR, 'input[value="Continue"]')

    BILLING_FIRST_NAME_FIELD = (By.ID, 'input-payment-firstname')
    BILLING_LAST_NAME_FIELD = (By.ID, 'input-payment-lastname')
    BILLING_ADDRESS_1_FIELD = (By.ID, 'input-payment-address-1')
    BILLING_CITY_FIELD = (By.ID, 'input-payment-city')
    BILLING_ZIP_FIELD = (By.ID, 'input-payment-postcode')
    BILLING_PHONE_FIELD = (By.ID, 'input-payment-telephone')
    BILLING_EMAIL_FIELD = (By.ID, 'input-payment-email')
    BILLING_PASSWORD = (By.ID, 'input-payment-password')
    BILLING_PASSWORD_CONFIRM = (By.ID, 'input-payment-confirm')
    BILLING_COMPANY = (By.ID, 'input-payment-company')
    BILLING_SELECT_COUNTRY = (By.ID, 'input-payment-country')
    BILLING_SELECT_REGION = (By.ID, 'input-payment-zone')
    BILLING_BTN_PRIVACY_POLICY= (By.CSS_SELECTOR,'div.pull-right input[name="agree"]')
    BILLING_BTN_CONTINUE = (By.ID, 'button-register')
    RADIO_SELECT_ADDRESS_DELIVERY = (By.CSS_SELECTOR, 'div.radio input[value= "existing"]')
    BTN_CONTINUE_DELIVERY_DETAILS = (By.ID, 'button-shipping-address')
    ELEMENT_FLAT_SHIPPING_RATE = (By.CSS_SELECTOR, 'div.panel-collapse.collapse.in div.panel-body div.radio label')
    BTN_CONTINUE_SHIPPING_METHOD = (By.ID, 'button-shipping-method')
    RADIO_CASH_ON_DELIVERY = (By.CSS_SELECTOR, 'input[value = "cod"]')
    BTN_CONTINUE_PAYMENT_METHOD = (By.ID, 'button-payment-method')
    BTN_TERMS_CONDITIONS = (By.CSS_SELECTOR, 'input[name= "agree"]')
    ELEMENTS_ORDER_CONFIRM = (By.CSS_SELECTOR, 'tfoot tr td.text-right')
    BTN_CONFIRM_ORDER = (By.ID , 'button-confirm')
    BTN_CONTINUE_SUCCESS_ORDER = (By.CSS_SELECTOR ,'div.buttons div.pull-right')
